apiVersion: v1
kind: Pod
metadata:
  name: custom-exp-pod
  namespace: test-suite
  labels:
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginx:stable-perl
    ports:
    - containerPort: 80
