apiVersion: v1
kind: Service
metadata:
  name: test-suite-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: test-suite
  ports:
    - protocol: TCP
      port: {{ .Values.testsuite.port }}
      targetPort: {{ .Values.testsuite.port }}
  type: ClusterIP

